export default interface User {
    id: number;
    userName: string;
    userNameKana: string;
    searchUserName: string;
    userType: number;
    debutDt: string;
    activityDt: string;
    activityNum: number;
    gender: number;
    officeId: number;
    officeName: string;
    areaId: number;
    areaNmae: string;
    selfIntroduction: string;
    loginAt: string;
    loginAtInt: number;
    updateAt: string;
    updateAtInt: number;
    memberNum: number;
    feeType: number;
    fee: number;
    comedyStyleIdList: Array<number>;
    comedyStyleNameList: Array<string>;
    comedyStyleNames: string;
    specialSkillIdList: Array<number>;
    specialSkillNameList: Array<string>;
    specialSkillNames: string;
  }
